### ISSUE TITLE
Google Geo Retrieval Fails - Add Location

### ISSUE THREAD

**Issue by dvolsysop** [christopherldotcom/Helios-Calendar#22]
With Google's new API requiring a paid subscription, geo retrieval codes for new locations no longer works.  You can, of course, look it up on Google maps and then manually input latitude and longitude coordinates but what was once automated no longer works.  API will need to be updated.

**Comment by chrislarrycarl** [comment]
Included in issue #8. Thanks!

**Comment by bklups** [comment]
In `inc/api/google/GetGeocode.php` just add `&key=yourapikey` to `$gSend = "maps.googleapis.com/maps/api/geocode/xml?address=" . urlencode($locString) . "&sensor=false"`
